### ISSUE TITLE
Stripe bindings v1.20.2 break Stripe Mock

### ISSUE THREAD

**Issue by peterkeen** [rebelidealist/stripe-ruby-mock#203]
Test failures:

```
  1) StripeMock::Instance behaves like Card Token Mocking Direct Token Creation generates and reads a card token for update customer
     Failure/Error: cus.save
     NoMethodError:
       undefined method `delete_if' for nil:NilClass
     Shared Example Group: "Card Token Mocking" called from ./spec/support/stripe_examples.rb:9
     # ./lib/stripe_mock/request_handlers/helpers/card_helpers.rb:27:in `add_card_to_object'
     # ./lib/stripe_mock/request_handlers/customers.rb:49:in `update_customer'
     # ./lib/stripe_mock/instance.rb:83:in `mock_request'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/card_token_examples.rb:32:in `block (3 levels) in <top (required)>'

  2) StripeMock::Instance behaves like Card Token Mocking Stripe::Token generates and reads a card token for update customer
     Failure/Error: cus.save
     NoMethodError:
       undefined method `delete_if' for nil:NilClass
     Shared Example Group: "Card Token Mocking" called from ./spec/support/stripe_examples.rb:9
     # ./lib/stripe_mock/request_handlers/helpers/card_helpers.rb:27:in `add_card_to_object'
     # ./lib/stripe_mock/request_handlers/customers.rb:49:in `update_customer'
     # ./lib/stripe_mock/instance.rb:83:in `mock_request'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/card_token_examples.rb:81:in `block (3 levels) in <top (required)>'

  3) StripeMock::Instance behaves like Card Token Mocking Stripe::Token generates a card token created from customer
     Failure/Error: cus.save
     NoMethodError:
       undefined method `delete_if' for nil:NilClass
     Shared Example Group: "Card Token Mocking" called from ./spec/support/stripe_examples.rb:9
     # ./lib/stripe_mock/request_handlers/helpers/card_helpers.rb:27:in `add_card_to_object'
     # ./lib/stripe_mock/request_handlers/customers.rb:49:in `update_customer'
     # ./lib/stripe_mock/instance.rb:83:in `mock_request'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/card_token_examples.rb:100:in `block (3 levels) in <top (required)>'

  4) StripeMock::Instance behaves like Customer API updates a stripe customer's card
     Failure/Error: original.save
     NoMethodError:
       undefined method `delete_if' for nil:NilClass
     Shared Example Group: "Customer API" called from ./spec/support/stripe_examples.rb:13
     # ./lib/stripe_mock/request_handlers/helpers/card_helpers.rb:27:in `add_card_to_object'
     # ./lib/stripe_mock/request_handlers/customers.rb:49:in `update_customer'
     # ./lib/stripe_mock/instance.rb:83:in `mock_request'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/customer_examples.rb:226:in `block (2 levels) in <top (required)>'

  5) StripeMock::Instance behaves like Invoice API updating an invoice updates a stripe invoice
     Failure/Error: invoice.save
     TypeError:
       0 is not a symbol
     Shared Example Group: "Invoice API" called from ./spec/support/stripe_examples.rb:15
     # ./spec/shared_stripe_examples/invoice_examples.rb:35:in `block (3 levels) in <top (required)>'

  6) StripeMock::Instance behaves like Customer Subscriptions updating a subscription overrides trial length when trial end is set
     Failure/Error: sub.save
     Stripe::InvalidRequestError:
       No such plan: {}
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./lib/stripe_mock/instance.rb:104:in `assert_existence'
     # ./lib/stripe_mock/request_handlers/subscriptions.rb:67:in `update_subscription'
     # ./lib/stripe_mock/instance.rb:83:in `mock_request'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/subscription_examples.rb:378:in `block (3 levels) in <top (required)>'

  7) StripeMock::Instance behaves like Customer Subscriptions updating a subscription returns without a trial when trial_end is set to 'now'
     Failure/Error: sub.save
     Stripe::InvalidRequestError:
       No such plan: {}
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./lib/stripe_mock/instance.rb:104:in `assert_existence'
     # ./lib/stripe_mock/request_handlers/subscriptions.rb:67:in `update_subscription'
     # ./lib/stripe_mock/instance.rb:83:in `mock_request'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/subscription_examples.rb:392:in `block (3 levels) in <top (required)>'

  8) StripeMock::Instance behaves like Customer Subscriptions updating a subscription changes an active subscription to a trial when trial_end is set
     Failure/Error: sub.save
     Stripe::InvalidRequestError:
       No such plan: {}
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./lib/stripe_mock/instance.rb:104:in `assert_existence'
     # ./lib/stripe_mock/request_handlers/subscriptions.rb:67:in `update_subscription'
     # ./lib/stripe_mock/instance.rb:83:in `mock_request'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/subscription_examples.rb:409:in `block (3 levels) in <top (required)>'

  9) StripeMock::Instance behaves like Customer Subscriptions updating a subscription raises error when trial_end is not an integer or 'now'
     Failure/Error: expect { sub.save }.to raise_error {|e|
       
       expected: 400
            got: 404
       
       (compared using ==)
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./spec/shared_stripe_examples/subscription_examples.rb:426:in `block (3 levels) in <top (required)>'

  10) StripeMock::Instance behaves like Customer Subscriptions metadata creates a stripe customer and subscribes them to a plan with meta data
     Failure/Error: expect(subscription.save).to be_a Stripe::Subscription
     Stripe::InvalidRequestError:
       No such plan: {}
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./lib/stripe_mock/instance.rb:104:in `assert_existence'
     # ./lib/stripe_mock/request_handlers/subscriptions.rb:67:in `update_subscription'
     # ./lib/stripe_mock/instance.rb:83:in `mock_request'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/subscription_examples.rb:582:in `block (3 levels) in <top (required)>'

  11) StripeMock Server behaves like Card Token Mocking Direct Token Creation generates and reads a card token for update customer
     Failure/Error: cus.save
     Jimson::Client::Error::ServerError:
       Server error -32099: Server application error: undefined method `delete_if' for nil:NilClass at /Users/peter/devel/stripe-ruby-mock/lib/stripe_mock/request_handlers/helpers/card_helpers.rb:27:in `add_card_to_object'
     Shared Example Group: "Card Token Mocking" called from ./spec/support/stripe_examples.rb:9
     # ./lib/stripe_mock/client.rb:17:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:16:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/card_token_examples.rb:32:in `block (3 levels) in <top (required)>'

  12) StripeMock Server behaves like Card Token Mocking Stripe::Token generates and reads a card token for update customer
     Failure/Error: cus.save
     Jimson::Client::Error::ServerError:
       Server error -32099: Server application error: undefined method `delete_if' for nil:NilClass at /Users/peter/devel/stripe-ruby-mock/lib/stripe_mock/request_handlers/helpers/card_helpers.rb:27:in `add_card_to_object'
     Shared Example Group: "Card Token Mocking" called from ./spec/support/stripe_examples.rb:9
     # ./lib/stripe_mock/client.rb:17:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:16:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/card_token_examples.rb:81:in `block (3 levels) in <top (required)>'

  13) StripeMock Server behaves like Card Token Mocking Stripe::Token generates a card token created from customer
     Failure/Error: cus.save
     Jimson::Client::Error::ServerError:
       Server error -32099: Server application error: undefined method `delete_if' for nil:NilClass at /Users/peter/devel/stripe-ruby-mock/lib/stripe_mock/request_handlers/helpers/card_helpers.rb:27:in `add_card_to_object'
     Shared Example Group: "Card Token Mocking" called from ./spec/support/stripe_examples.rb:9
     # ./lib/stripe_mock/client.rb:17:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:16:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/card_token_examples.rb:100:in `block (3 levels) in <top (required)>'

  14) StripeMock Server behaves like Customer API updates a stripe customer's card
     Failure/Error: original.save
     Jimson::Client::Error::ServerError:
       Server error -32099: Server application error: undefined method `delete_if' for nil:NilClass at /Users/peter/devel/stripe-ruby-mock/lib/stripe_mock/request_handlers/helpers/card_helpers.rb:27:in `add_card_to_object'
     Shared Example Group: "Customer API" called from ./spec/support/stripe_examples.rb:13
     # ./lib/stripe_mock/client.rb:17:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:16:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/customer_examples.rb:226:in `block (2 levels) in <top (required)>'

  15) StripeMock Server behaves like Customer Subscriptions updating a subscription overrides trial length when trial end is set
     Failure/Error: sub.save
     Stripe::InvalidRequestError:
       No such plan: {}
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./lib/stripe_mock/client.rb:20:in `block (2 levels) in mock_request'
     # ./lib/stripe_mock/client.rb:17:in `tap'
     # ./lib/stripe_mock/client.rb:17:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:16:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/subscription_examples.rb:378:in `block (3 levels) in <top (required)>'

  16) StripeMock Server behaves like Customer Subscriptions updating a subscription returns without a trial when trial_end is set to 'now'
     Failure/Error: sub.save
     Stripe::InvalidRequestError:
       No such plan: {}
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./lib/stripe_mock/client.rb:20:in `block (2 levels) in mock_request'
     # ./lib/stripe_mock/client.rb:17:in `tap'
     # ./lib/stripe_mock/client.rb:17:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:16:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/subscription_examples.rb:392:in `block (3 levels) in <top (required)>'

  17) StripeMock Server behaves like Customer Subscriptions updating a subscription changes an active subscription to a trial when trial_end is set
     Failure/Error: sub.save
     Stripe::InvalidRequestError:
       No such plan: {}
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./lib/stripe_mock/client.rb:20:in `block (2 levels) in mock_request'
     # ./lib/stripe_mock/client.rb:17:in `tap'
     # ./lib/stripe_mock/client.rb:17:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:16:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/subscription_examples.rb:409:in `block (3 levels) in <top (required)>'

  18) StripeMock Server behaves like Customer Subscriptions updating a subscription raises error when trial_end is not an integer or 'now'
     Failure/Error: expect { sub.save }.to raise_error {|e|
       
       expected: 400
            got: 404
       
       (compared using ==)
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./spec/shared_stripe_examples/subscription_examples.rb:426:in `block (3 levels) in <top (required)>'

  19) StripeMock Server behaves like Customer Subscriptions metadata creates a stripe customer and subscribes them to a plan with meta data
     Failure/Error: expect(subscription.save).to be_a Stripe::Subscription
     Stripe::InvalidRequestError:
       No such plan: {}
     Shared Example Group: "Customer Subscriptions" called from ./spec/support/stripe_examples.rb:22
     # ./lib/stripe_mock/client.rb:20:in `block (2 levels) in mock_request'
     # ./lib/stripe_mock/client.rb:17:in `tap'
     # ./lib/stripe_mock/client.rb:17:in `block in mock_request'
     # ./lib/stripe_mock/client.rb:86:in `timeout_wrap'
     # ./lib/stripe_mock/client.rb:16:in `mock_request'
     # ./lib/stripe_mock/api/client.rb:35:in `redirect_to_mock_server'
     # ./lib/stripe_mock/api/instance.rb:22:in `call'
     # ./lib/stripe_mock/api/instance.rb:22:in `block in alias_stripe_method'
     # ./spec/shared_stripe_examples/subscription_examples.rb:582:in `block (3 levels) in <top (required)>'

Finished in 31.62 seconds (files took 0.91173 seconds to load)
490 examples, 19 failures, 2 pending

Failed examples:

rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Card Token Mocking Direct Token Creation generates and reads a card token for update customer
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Card Token Mocking Stripe::Token generates and reads a card token for update customer
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Card Token Mocking Stripe::Token generates a card token created from customer
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Customer API updates a stripe customer's card
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Invoice API updating an invoice updates a stripe invoice
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Customer Subscriptions updating a subscription overrides trial length when trial end is set
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Customer Subscriptions updating a subscription returns without a trial when trial_end is set to 'now'
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Customer Subscriptions updating a subscription changes an active subscription to a trial when trial_end is set
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Customer Subscriptions updating a subscription raises error when trial_end is not an integer or 'now'
rspec ./spec/instance_spec.rb:4 # StripeMock::Instance behaves like Customer Subscriptions metadata creates a stripe customer and subscribes them to a plan with meta data
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Card Token Mocking Direct Token Creation generates and reads a card token for update customer
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Card Token Mocking Stripe::Token generates and reads a card token for update customer
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Card Token Mocking Stripe::Token generates a card token created from customer
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Customer API updates a stripe customer's card
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Customer Subscriptions updating a subscription overrides trial length when trial end is set
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Customer Subscriptions updating a subscription returns without a trial when trial_end is set to 'now'
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Customer Subscriptions updating a subscription changes an active subscription to a trial when trial_end is set
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Customer Subscriptions updating a subscription raises error when trial_end is not an integer or 'now'
rspec ./spec/server_spec.rb:4 # StripeMock Server behaves like Customer Subscriptions metadata creates a stripe customer and subscribes them to a plan with meta data
```

The breaking change was introduced in stripe/stripe-ruby#217, specifically in commit 03abd88f0c4d15f466f18b1d324d57489db2a51b. I haven't narrowed down exactly what the problem is, but I suspect we're just no longer handling nested hashes like the parent code expects.

**Comment by JoshSmith** [comment]
Looks like I'm seeing the same sorts of test failures.

**Comment by theoretick** [comment]
Yep, I'm getting this too.

Interesting/possibly-related bit: I get a different error when I try an immediate fetch and save:
```ruby
[7] website(#<Subscriptions::UpdateService>) »  Stripe::Customer.retrieve('test_cus_3').save
TypeError: 0 is not a symbol
from /home/theoretick/.gem/ruby/2.1.2/gems/stripe-1.20.3/lib/stripe/stripe_object.rb:215:in `define_method'
```

From what I can tell it is some issue with how stripe-ruby-mock is passing the serialized values to the update action:
```ruby
From: /home/theoretick/.gem/ruby/2.1.2/gems/stripe-1.20.3/lib/stripe/api_operations/update.rb @ line 11 Stripe::APIOperations::Update#save:

     4: def save(params={})
     5:   values = self.class.serialize_params(self).merge(params)
     6:
     7:   if values.length > 0
     8:     values.delete(:id)
     9:
    10:     response, opts = request(:post, url, values)
 => 11:     binding.pry
    12:     refresh_from(response, opts)
    13:   end
    14:   self
    15: end

[1] website(#<Stripe::Customer>  »  values
=> {
           :card => "test_tok_5",
        :sources => {
    :data => nil
  },
  :subscriptions => {
    :data => {
      0 => {
            :plan => {},
        :metadata => {}
      }
    }
  }
}
[2] website(#<Stripe::Customer>) »  response
=> {
            :email => "johnny@on_the.spot",
      :description => "a description",
           :object => "customer",
          :created => 1372126710,
               :id => "test_cus_3",
         :livemode => false,
       :delinquent => false,
         :discount => nil,
  :account_balance => 0,
          :sources => {
    :data => nil
  },
    :subscriptions => {
    :data => {
      0 => {
            :plan => {},
        :metadata => {}
      }
    }
  },
   :default_source => "test_cc_2",
             :card => "test_tok_5"
}
```

As can be seen above `subscriptions.data` is a hash, not an array.  This eventually hits `convert_to_stripe_object` and freaks out trying to dynamically create a method with `0`, leading to the above `TypeError`

**Comment by JonCrawford** [comment]
:wave: Any progress here?

**Comment by alexmamonchik** [comment]
all this errors already fixed in `stripe-1.21.0` branch. `Master` branch still working on stripe 1.20.1. I recommend  switch to new branch or wait merging 1.21.0 to master.

**Comment by psusmars** [comment]
I'm still receiving the "0 is not a symbol" error when I update a user with a new valid source/credit card token on the `stripe-1.21.0` branch. I'm using stripe 1.21.0. Here's the code I'm using:
```
token = stripe_helper.generate_card_token(number: '4012888888881881')
customer = Stripe::Customer.create({source: token, email: 'test@test.com'})
customer = Stripe::Customer.retrieve(customer.id)
customer.source = stripe_helper.generate_card_token(number: '4242424242424242')
customer.save #error
```

**Comment by kathyonu** [comment]
@psusmars I just ran this code, exactly as yours, and it works perfectly : 
```ruby
token = stripe_helper.generate_card_token(number: '4012888888881881')
customer = Stripe::Customer.create({source: token, email: 'test@test.com'})
customer = Stripe::Customer.retrieve(customer.id)
customer.source = stripe_helper.generate_card_token(number: '4242424242424242')
customer.save 
=> #<Stripe::Customer:0x3fd26838d914 id=test_cus_5> JSON: {
  "id": "test_cus_5",
  "email": "test@test.com",
  "description": "an auto-generated stripe customer data mock",
  etc.
```
May I ask, is this issue resolved for you, and if not .. can you please show me the code you are running, and its results ?  Thank You.

**Comment by psusmars** [comment]
@kathyonu I pulled out my exact scenario with any calls that I make to stripe:

```
Stripe::Plan.create(
  id: "XXX",
  amount: 1200,
  currency: 'usd',
  interval: 'month',
  name: "test",
)
customer_attributes = {
                description: "TEST",
                email: "test@test.com",
                source:  stripe_helper.generate_card_token(number: '4012888888881881')
              }
customer = Stripe::Customer.create(customer_attributes)
sub = customer.subscriptions.create(plan: "XXX", prorate: true)
source = customer.sources.retrieve(customer.default_source)
# confirms the check

customer = Stripe::Customer.retrieve(customer.id)
customer.source = stripe_helper.generate_card_token(number: '4242424242424242')
customer.save #errors here

```

**Comment by kathyonu** [comment]
@psusmars Once again, your code works on my system. I provide you the full code with the tests in place, below.  Can you please test this in your system, and show me the results if it fails ? 

Also, is there any chance at all that you have not actually upgraded the gem to 1.21.0 ??  or your Gemfile.lock is still using it ?  Here is what I have, and it passes : 
```ruby
require 'stripe_mock'

describe 'Subscription API' do

  let(:stripe_helper) { StripeMock.create_test_helper }

  before(:each) do
    StripeMock.start
  end

  after(:each) do
    StripeMock.stop
  end

   it 'creates a plan, a customer, no charge, add a new card' do
    Stripe::Plan.create(
      id:       'platinum',
      amount:   900,
      currency: 'usd',
      interval: 'month',
      name:     'Platinum',
    )
    customer_attributes = {
      email: 'test@test.com',
      source: stripe_helper.generate_card_token(
        last4: '1881',
        exp_month: 11,
        exp_year: 2021,
        description: 'entering my card number',
      )
    }
    customer = Stripe::Customer.create(customer_attributes)
    subscription = customer.subscriptions.create(plan: 'platinum', prorate: true)
    source       = customer.sources.retrieve(customer.default_source)
    expect(customer.id).to match /^test_cus_3/
    expect(subscription.id).to match /^test_su_4/
    expect(source.id).to match /^test_cc_2/

    customer = Stripe::Customer.retrieve(customer.id)
    expect(customer.id).to match /^test_cus_3/
    expect(customer.sources.first.id).to match /^test_cc_2/
    expect(customer.sources.data.first.last4).to eq '1881'
    expect(customer.subscriptions.first.id).to match /^test_su_4/
    expect(customer.subscriptions.data.first.id).to match /^test_su_4/

    customer.subscriptions { include[]=data }
    customer.subscriptions.data { include[]=plans }
    expect(customer.subscriptions.first.plan.name).to eq 'Platinum'
    expect(customer.subscriptions.first.id).to match /^test_su_4/
    expect(customer.subscriptions.first.customer).to match /^test_cus_3/
    expect(customer.subscriptions.first.plan.id).to eq 'platinum'
    expect(customer.sources.total_count).to eq 1

    new_card_token = stripe_helper.generate_card_token(
            last4: '4242', 
        exp_month: 11, 
         exp_year: 2022, 
      description: 'new card'
    )
    customer.sources.create(source: new_card_token)
    customer.save
    twocardcustomer = Stripe::Customer.retrieve(customer.id)
    customer.sources { include[]=total_count }
    expect(twocardcustomer.sources.total_count).to eq 2
    expect(twocardcustomer.id).to match /^test_cus_3/
    expect(twocardcustomer.email).to eq 'test@test.com'
    expect(twocardcustomer.description).to eq 'an auto-generated stripe customer data mock'
    expect(twocardcustomer.sources.first.id).to match /^test_cc_2/
    expect(twocardcustomer.sources.data.first.id).to match /^test_cc_2/
    expect(twocardcustomer.sources.data.second.id).to match /^test_cc_6/
    expect(twocardcustomer.default_source).to match /^test_cc_2/
    expect(twocardcustomer.sources.data[0].last4).to eq '1881'
    expect(twocardcustomer.sources.data[0].exp_month).to eq 11
    expect(twocardcustomer.sources.data[0].exp_year).to eq 2021
    expect(twocardcustomer.sources.data[1].last4).to eq '4242'
    expect(twocardcustomer.sources.data[1].exp_month).to eq 11
    expect(twocardcustomer.sources.data[1].exp_year).to eq 2022
    expect(twocardcustomer.object).to eq 'customer'
    expect(twocardcustomer.livemode).to eq false
  end
end
```
Does this resolves things for you ?

**Comment by psusmars** [comment]
@kathyonu I took your code exactly, copied it to a new ruby vm and was able to get it to run on the 1.21.0 branch. Thanks for responding, I apologize if I wasted any of your time.

**Comment by kathyonu** [comment]
@psusmars  again, your code works on my system. I provide you the full code with the tests in place, below.  Can you please test this in your system, and show me the results if it fails ? 

Also, is there any chance at all that you have not actually upgraded the gem to 1.21.0 ??  or your Gemfile.lock is still using it ?  Here is what I have, and it passes : 
```ruby
require 'stripe_mock'

describe 'Subscription API' do

  let(:stripe_helper) { StripeMock.create_test_helper }

  before(:each) do
    StripeMock.start
  end

  after(:each) do
    StripeMock.stop
  end

   it 'creates a plan, a customer, no charge, add a new card' do
    Stripe::Plan.create(
      id:       'platinum',
      amount:   900,
      currency: 'usd',
      interval: 'month',
      name:     'Platinum',
    )
    customer_attributes = {
      email: 'test@test.com',
      source: stripe_helper.generate_card_token(
        last4: '1881',
        exp_month: 11,
        exp_year: 2021,
        description: 'entering my card number',
      )
    }
    customer = Stripe::Customer.create(customer_attributes)
    subscription = customer.subscriptions.create(plan: 'platinum', prorate: true)
    source       = customer.sources.retrieve(customer.default_source)
    expect(customer.id).to match /^test_cus_3/
    expect(subscription.id).to match /^test_su_4/
    expect(source.id).to match /^test_cc_2/

    customer = Stripe::Customer.retrieve(customer.id)
    expect(customer.id).to match /^test_cus_3/
    expect(customer.sources.first.id).to match /^test_cc_2/
    expect(customer.sources.data.first.last4).to eq '1881'
    expect(customer.subscriptions.first.id).to match /^test_su_4/
    expect(customer.subscriptions.data.first.id).to match /^test_su_4/

    customer.subscriptions { include[]=data }
    customer.subscriptions.data { include[]=plans }
    expect(customer.subscriptions.first.plan.name).to eq 'Platinum'
    expect(customer.subscriptions.first.id).to match /^test_su_4/
    expect(customer.subscriptions.first.customer).to match /^test_cus_3/
    expect(customer.subscriptions.first.plan.id).to eq 'platinum'
    expect(customer.sources.total_count).to eq 1

    new_card_token = stripe_helper.generate_card_token(
            last4: '4242', 
        exp_month: 11, 
         exp_year: 2022, 
      description: 'new card'
    )
    customer.sources.create(source: new_card_token)
    customer.save
    twocardcustomer = Stripe::Customer.retrieve(customer.id)
    customer.sources { include[]=total_count }
    expect(twocardcustomer.sources.total_count).to eq 2
    expect(twocardcustomer.id).to match /^test_cus_3/
    expect(twocardcustomer.email).to eq 'test@test.com'
    expect(twocardcustomer.description).to eq 'an auto-generated stripe customer data mock'
    expect(twocardcustomer.sources.first.id).to match /^test_cc_2/
    expect(twocardcustomer.sources.data.first.id).to match /^test_cc_2/
    expect(twocardcustomer.sources.data.second.id).to match /^test_cc_6/
    expect(twocardcustomer.default_source).to match /^test_cc_2/
    expect(twocardcustomer.sources.data[0].last4).to eq '1881'
    expect(twocardcustomer.sources.data[0].exp_month).to eq 11
    expect(twocardcustomer.sources.data[0].exp_year).to eq 2021
    expect(twocardcustomer.sources.data[1].last4).to eq '4242'
    expect(twocardcustomer.sources.data[1].exp_month).to eq 11
    expect(twocardcustomer.sources.data[1].exp_year).to eq 2022
    expect(twocardcustomer.object).to eq 'customer'
    expect(twocardcustomer.livemode).to eq false
  end
end
```
Does this resolves things for you ?

**Comment by psusmars** [comment]
@kathyonu I had meant to not delete my post. I just ran your exact code against my machine that was generating the errors and I saw 0 issues. It should be noted that I was running my code within a "MiniTest" generated test. So I'll just put these into Rspect tests in the app that is having the issues.

**Comment by kathyonu** [comment]
@psusmars : mee thinks you misunderstand, that note to you, removed a repeated posting, is me doing exactly that, i somehow duplicated that big code post, so i removed it  and just let you know by changing the post.  Also, i have no clue why you think you might have wasted me time.  my gig on these things is, if i can solve your problem, i learn in the process, and i can apply the learnings to our production app if applicable.

**Comment by kathyonu** [comment]
I believe this issue can be closed.
